AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla para crear instancia de EC2 y grupo de seguridad
Resources:
  cloudformationSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Grupo de Seguridad para el puerto 8080
      GroupName: AppServerSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  cloudformationEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06aa3f7caf3a30282 #ubuntu20.04
      InstanceType: t2.micro #free-tiery
      KeyName: vockey # nombre del par de claves del usuario
      SecurityGroupIds:
        - !Ref 'cloudformationSG'
      IamInstanceProfile: LabInstanceProfile